name: 'Tests: node.js: native'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '> 19'
      type: majors
      continue-on-error: true
      command: npm run test:native

  node:
    name: 'node, native tests'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
